/**********************************************************************************************************
 * 
 * This demo showcase creating a GATT database using a predefined attribute table.
 * It acts as a GATT server and can send adv data, be connect client.
 * Run the gatt_client demo, the client demo will automaticlly connect to the gatt_server_service.
 * Client demo will enable GATT server's notify after connection. The two devices will then exchange data.
 *  
***********************************************************************************************************/


/**********************************************************************************************************
 * Includes are required for the "FreeRTOS" and underlying system components to run, including logging and library
 * to store data in non-volatile flash mempory.
 * `bt.h`: impliments BT controller and VHCL configuration procedures from the host side.
 * `eso_bt_main.h` : impliments initialization and enabling of the Bluedroid stack.
 * `esp_gap_ble_api.h` :  impliments GAP configurations such as advertising and connection parameters.
 * `esp_gatts_api.h` : impliments GATT server configurations such as creating services and characteristics.
 */
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_bt.h"

#include "esp_gap_ble_api.h"
#include "esp_gatts_api.h"
#include "esp_bt_main.h"
#include "esp_bt_device.h"
#include "gatt_server_wls.h"
#include "esp_gatt_common_api.h"

#define GATTS_TABLE_TAG "GATTS_TABLE"

/*
Finally, the Application Profiles are registered using the Application ID, which is an user-assigned number to identify each profile. 
In this way, multiple Application Profiles can run in one server. Applicatio ID is 0x55,
*/

#define PROFILE_NUM			1
#define PROFILE_APP_IDX		0
#define ESP_APP_ID			0x55
#define SAMPLE_DEVICE_NAME	"ESP_GATTS"
#define SCV_INST_ID			0

/* Application Profile */
/* 
Application profile was designed to have one service and one characteristic, and that the characteristic has one descriptor.
*/

struct gatts_profile_inst {
	esp_gatts_cd_t gatts_cd;
	uint16_t gatts_if;				//	GATT Interface
	uint16_t app_id;				//	Application ID
	uint16_t conn_id;				//	Connection ID
	uint16_t service_handle;		//	Service handle
	esp_gatt_srvc_id_t service_id;	//	Service ID
	uint16_t char_handle;			//	Character handle
	esp_bt_uuid_t char_uuid;		//	Characteristic UUID
	esp_gatt_perm_t perm;			//	Attribute permission
	esp_gatt_char_prop_t prioerty;	//	Characteristic properties
	uint16_t descr_handle;			//	Client Charecteristic Configuration descriptor handle
	esp_bt_uuid_t descr_uuid;		//	Client Charecteristic Configuration descriptor UUID
};

/* Application Profile Structure Implimentation */




/* GATTS Event Handler */
static void gatts_event_handler(esp_gatts_cd_event_t event, esp_gatt_if_t gatts_if, esp_ble_gatts_cd_param_t *param)
{
	/* If event is register event, store the gatts_if for each profile*/
}

/* GAP Event Handler */
static void gap_event_handler()
{

}



void app_main(void)
{
	esp_err_t ret;

	/* Initialize NVS */
	/* The main function starts by initializing the non-volatile storage library */
	ret = nvs_flash_init();
	if (ret == ESP_ERR_NVS_NO_FREE_PAGE || ret == ESP_ERR_NVS_NEW_VERSION_FOUND){
		ESP_ERROR_CHECK(nvs_flash_erase());
		ret = nvs_flash_init()
	}
	ESP_ERROR_CHECK( ret );

	ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));

	/* esp bluetooth controller initialize */

	/* The main function initializes the BT controller by first creating a BT controller configuration structure,
	named esp_bt_controller_config_t with default settings generated by the BT_CONTROLLER_INIT_CONFIG_DEFAULT() macro 
	
	The BT controller implements the "Host Controller Interface (HCI)" on the controller side, 
	the Link Layer (LL) and the Physical Layer (PHY).  The BT Controller is invisible to the user applications,
	and deals with the lower layers of the BLE stack.

	The controller configuration includes setting the BT controller stack size, priority and HCI baud rate. 
	With the settings created, the BT controller is initialized and enabled with the esp_bt_controller_init() function:

	*/
	esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
	ret = esp_bt_controller_init(&bt_cfg);
	if (ret) {
		ESP_LOGE(GATTS_TABLE_TAG, "%s enable controller failed", __func__, esp_err_to_name(ret));
		return;
	}

	ESP_LOGI(GATTS_TABLE_TAG, "%s init bluetooth", __func__, esp_err_to_name(ret));

	/* esp bluetooth controller enable */
	/*
	Next, the controller is enabled in BLE Mode. (Other Modes:  Bluetooth not running, BLE mode, BT Classic mode, Dual mode) 
	*/
	ret = esp_bt_controller_enable(ESP_BT_MODE_BLE);
	if (ret) {
		ESP_LOGE(GATTS_TABLE_TAG, "%s enable controller failed: %s", __func__, esp_err_to_name(ret));
		return;
	}

	/* esp bluedroid init */
	/* After the initialization of the BT controller, the Bluedroid stack, which includes the common definitions and APIs for both BT Classic and BLE, is initialized and enabled.
	
	The Bluetooth stack is up and running at this point in the program flow, however the functionality of the application has not been defined yet.
	*/
	ret = esp_bluedroid_init();
	if (ret) {
		ESP_LOGE(GATTS_TABLE_TAG, "%s int bluetooth failed: %s", __func__, esp_err_to_name(ret));
		return;
	}

	/* esp bluedriod enable */
	ret = esp_bluedriod_enable();
	if (ret) {
		ESP_LOGE(GATTS_TABLE_TAG, "%s enable bluetooth failed: %s", __func__, esp_err_to_name(ret));
		return;
	}

	/*
	The functionality is defined by reacting to events such as what happens when another device tries to read or write parameters and establish a connection. 
	GAP and GATT event handler managers.

	The application needs to register a callback function for each event handler in order to let the application know which functions are going to handle the GAP and GATT events.

	The functions gatts_event_handler() and gap_event_handler() handle all the events that are pushed to the application from the BLE stack.
	*/
	ret = esp_ble_gatts_register_callback(gatts_event_handler);
	if (ret){
		ESP_LOGE(GATTS_TABLE_TAG, "gatts register error, error code = %x", ret);
		return;
	}

	ret = esp_ble_gap_register_callback(gap_event_handler);
	if (ret){
		ESP_LOGE(GATTS_TABLE_TAG, "gap app register error, error code = %x", ret);
		return;
	}
	
	/*  */
	ret = esp_ble_gatts_app_register(ESP_APP_ID);
	if (ret){
		ESP_LOGE(GATTS_TABLE_TAG, "gatts app register error, error code = %x", ret);
	}

	/*  */
	esp_err_t local_mut_ret = esp_ble_gatt_set_local_mtu(500);
	if (local_mut_ret){
		ESP_LOGE(GATTS_TABLE_TAG, "set local MTU failed, error code = %x", local_mut_ret);
	}
}
